name: o_dynamic
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.6

  # router
  go_router: ^14.2.3

  # state management
  flutter_riverpod: ^2.5.1

  # models
  json_annotation: ^4.9.0

  # network
  dio: ^5.4.2+1

  # webview
  webview_flutter: ^4.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  json_serializable: ^6.8.0
  build_runner: ^2.4.9
  flutter_lints: ^3.0.0


# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/config.json
